### ISSUE TITLE
Feature:  user can select an answer for each question

### ISSUE THREAD

**Issue by imtiaz101325** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#13]
- [x] there need to be some sort of input in the Q/A pages
- [x] there needs to be a input handler 
- [x] #17
- [x] this progress needs to be save in data.js or the model

**Comment by M-Hajjar** [comment]
me and Beimnet working on this we completed most tasks such as 
let the user have an input on each button 
we have added a score handler but we need it to save the data 
and also we are dealing with the feedback event


note: in order to see what's going on the app we use the previous UI until we all agree on one

**Comment by beimnet11** [comment]
its good work. fine with me

**Comment by azizsigar** [comment]
i like this can you merge it i can ocntuniue from there. i would like to add feedback handeller.

**Comment by imtiaz101325** [comment]
Closed by #18
