### ISSUE TITLE
checking questions

### ISSUE THREAD

**Issue by azizsigar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#22]
buttons are need to be clickable
use radio tag html
function =(
conditions(if answer===selected)
**if** correct 
1 score++

3 if no more question show ending page
**else** 
4 do nothing
)
5 checking with go next questions (addeventlistener click, function)
@M-Hajjar  can you make refactorize the codes

**Comment by M-Hajjar** [comment]
for this issue is all done 
- [x] score++
- [x] if no more question show ending page
- [x] checking with go next questions (addeventlistener click, function)

and it has been pushed to main branch through PR "add js files https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/pull/28"
