### ISSUE TITLE
restart button

### ISSUE THREAD

**Issue by azizsigar** [imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break#24]
if no more question show ending page

**Comment by M-Hajjar** [comment]
this issue is done 
at the end of the quiz ( no more question ) it will show a button that says " go home " or " try again "
and both of them will restart the quiz app 
and it has been pushed to main branch through PR "add js files https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/pull/28"
